<?php

/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Darcy Clarke. http://themify.me
/*  				Copyright (C) 2010 Themify
/*
/***************************************************************************/

/* 	Database Functions
/***************************************************************************/

	///////////////////////////////////////////
	// Initialize DB - Create Row if needed
	///////////////////////////////////////////
	function init_db(){
		global $wpdb, $theme;
		if(!$wpdb->get_row("SELECT * FROM ".$wpdb->options." WHERE option_name = '".$theme['Name']."_themify_data'")){
			$wpdb->query("INSERT INTO ".$wpdb->options." SET option_name = '".$theme['Name']."_themify_data', option_value = '', autoload = 'yes'");
		}
	}
		
	///////////////////////////////////////////
	// Set/Save Data
	///////////////////////////////////////////
	function set_data($data){
		global $wpdb, $theme;
		foreach($data as $name => $value){
			if($name == 'save' || $name == 'page'){
				unset($data[$name]);	
			}
		}
		$result = $wpdb->query("UPDATE ".$wpdb->options." SET option_value = '".base64_encode(serialize($data))."' WHERE option_name = '".$theme['Name']."_themify_data'");
		return $data;
	}
		
	///////////////////////////////////////////
	// Get/Grab Data
	///////////////////////////////////////////
	function get_data(){
		global $wpdb, $theme;
		$result = $wpdb->get_row("SELECT * FROM ".$wpdb->options." WHERE option_name = '".$theme['Name']."_themify_data'");
		$data = unserialize(base64_decode($result->option_value));
		if(is_array($data) && count($data) >= 1){
			foreach($data as $name => $value){
				$data[$name] = stripslashes($value);	
			}
		}
		return $data;
	}
	
?>