<?php

/***************************************************************************/
/* 
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Darcy Clarke. http://themify.me
/*  				Copyright (C) 2010 Themify
/*
/***************************************************************************/

/* 	AJAX
/***************************************************************************/
	
	error_reporting(0);
	
	$script = $_SERVER['SCRIPT_FILENAME'];
	$wppos = stripos($_SERVER['SCRIPT_FILENAME'],"wp-content");
	$finalstr = substr($_SERVER['SCRIPT_FILENAME'],0,$wppos);
	require_once($finalstr.'wp-config.php');
	require_once($finalstr.'wp-load.php');
	require_once($finalstr.'wp-includes/wp-db.php');
	require_once('themify-utils.php');
	require_once('themify-config.php');
	
	///////////////////////////////////////////
	// Save Settings
	///////////////////////////////////////////
	function themify_save(){
		$data = explode("&", $_POST['data']);
		$temp = array();
		foreach($data as $a){
			$v = explode("=", $a);
			$temp[$v[0]] = urldecode( str_replace("+"," ",preg_replace('/%([0-9a-f]{2})/ie', "chr(hexdec('\\1'))", urlencode($v[1]))) );
		}
		set_data($temp);
		echo "Saved your settings";
	}
	if($_GET['save']){
		themify_save();
	}
	add_action('wp_ajax_themify_save', 'themify_save');
	
	///////////////////////////////////////////
	// Grab Settings
	///////////////////////////////////////////
	function themify_pull(){
		print_r(get_data());		
	}
	if($_GET['pull']){
		themify_pull();
	}
	add_action('wp_ajax_themify_pull', 'themify_pull');
	
	///////////////////////////////////////////
	// Reset Styling
	///////////////////////////////////////////
	function themify_reset_styling(){
		$data = explode("&", $_POST['data']);
		$temp_data = array();
		foreach($data as $a){
			$v = explode("=", $a);
			$temp_data[$v[0]] = str_replace("+"," ",preg_replace('/%([0-9a-f]{2})/ie', "chr(hexdec('\\1'))", $v[1]));
		}
		$temp = array();
		foreach($temp_data as $key => $val){
			if(strpos($key, 'styling') === false){
				$temp[$key] = $val;
			}
		}
		print_r(set_data($temp));	
	}
	if($_GET['reset-styling']){
		themify_reset_styling();
	}
	add_action('wp_ajax_themify_reset_styling', 'themify_reset_styling');
	
	///////////////////////////////////////////
	// Reset Setting
	///////////////////////////////////////////
	function themify_reset_setting(){
		$data = explode("&", $_POST['data']);
		$temp_data = array();
		foreach($data as $a){
			$v = explode("=", $a);
			$temp_data[$v[0]] = str_replace("+"," ",preg_replace('/%([0-9a-f]{2})/ie', "chr(hexdec('\\1'))", $v[1]));
		}
		$temp = array();
		foreach($temp_data as $key => $val){
			if(strpos($key, 'setting') === false){
				$temp[$key] = $val;
			}
		}
		print_r(set_data($temp));	
	}
	if($_GET['reset-setting']){
		themify_reset_setting();
	}
	add_action('wp_ajax_themify_reset_setting', 'themify_reset_setting');
	
	///////////////////////////////////////////
	// Import
	///////////////////////////////////////////
	function themify_import(){
		if(!empty($_FILES)) {
			if(!is_dir(TEMPLATEPATH.'/themify/temp')){		
				mkdir(TEMPLATEPATH.'/themify/temp', 0777);
			}
			if(move_uploaded_file($_FILES['Filedata']['tmp_name'], TEMPLATEPATH.'/themify/temp/'.basename($_FILES['Filedata']['name']))){
				$file = basename($_FILES['Filedata']['name']);
				$ext = substr(strrchr($file, '.'), 1);
				$dir = "temp/";
				if($ext == 'zip' || $ext == 'rar'){
					themify_extract_zip(TEMPLATEPATH.'/themify/'.$dir.$file);
				} else if($ext == 'txt'){
					$handler = fopen($dir.$file, 'r');
					if(filesize($dir.$file) > 0){
						$data = fread($handler, filesize($dir.$file));
						set_data(unserialize($data));
					}
					fclose($fh);	
				}
				$handle = opendir("temp/");
   				while($file = readdir($handle)){
      				if($file != "." && $file != ".."){
            			unlink("temp/".$file);
					}
				}
				rmdir("temp/");
				echo "true";
			} else {
				echo "false";
			}
		}	
	}
	if($_GET['import']){
		themify_import();
	}
	add_action('wp_ajax_themify_import', 'themify_import');
	
	///////////////////////////////////////////
	// Extract
	///////////////////////////////////////////
	function themify_export(){
		global $theme;
		if(class_exists('ZipArchive')){
			$datafile = "data_export.txt";
			$handler = fopen($datafile, 'w');
			fwrite($handler,serialize(get_data()));
			fclose($handler);
			$files_to_zip = array(
				'../config.xml',
				'../custom_modules.php',
				'../custom_widgets.php',
				$datafile
			);
			$file = $theme['Name'].'_themify_export_'.date("Y-m-d").'.zip';
			$result = themify_create_zip($files_to_zip, $file, true);
			if($result){
				themify_force_download($file);
				unlink($datafile);
				unlink($file);
			}
		} else {
			if(ini_get('zlib.output_compression')) { 
				ini_set('zlib.output_compression', 'Off');	
			}
			header('Pragma: public');
			header('Expires: 0');
			header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
			header('Cache-Control: private',false);
			header('Content-Type: application/force-download');
			header('Content-Disposition: attachment; filename="'.$theme['Name'].'_themify_export_'.date("Y-m-d").'.txt"');
			header('Content-Transfer-Encoding: binary');
			echo serialize(get_data());
			exit();
		}
	}
	if($_GET['export']){
		themify_export();		
	}
	add_action('wp_ajax_themify_reset_setting', 'themify_reset_setting');
	
	///////////////////////////////////////////
	// Upload Image
	///////////////////////////////////////////
	function themify_upload(){
		if(!empty($_FILES)) {
			if(!isset($_POST['target']) || $_POST['target'] == ''){
				$target = TEMPLATEPATH.'/uploads/';
			} else {
				$target = TEMPLATEPATH.'/'.$_POST['target'];
			}	
			$target = rtrim($target, "/");
			$check = false;
			if(!is_dir($target)){		
				if(!mkdir($target, 0777, true)){
					echo "false";	
				} else {
					$check = true; 	
				}
			} else {
				$check = true;	
			}
			if($check){
				if(move_uploaded_file($_FILES['Filedata']['tmp_name'], $target."/".str_replace(" ", "-", basename($_FILES['Filedata']['name'])))){
					echo str_replace(" ", "-", basename($_FILES['Filedata']['name']));
				} else {
					echo "false";
				}
			}
		}
	}
	if($_GET['upload']){
		themify_upload();
	}
	add_action('wp_ajax_themify_upload', 'themify_upload');
	
	///////////////////////////////////////////
	// Upload Image - To Wordpress Uploads
	///////////////////////////////////////////
	function themify_upload_wordpress(){
		if(!empty($_FILES)){
			$filename = $_FILES["Filedata"]["tmp_name"];
			$file = fopen($filename, 'r');
			$data = fread($file, filesize($filename));
			fclose($file);
			$upload = wp_upload_bits($_FILES["Filedata"]["name"], null, $data);
			if($upload['error']){
				echo $upload['error'];	
			} else {
				echo $upload['url'];
			}
		} else {
			echo "false";	
		}	
	}
	if($_GET['upload-wordpress']){
		themify_upload_wordpress();	
	}
	add_action('wp_ajax_themify_upload_wordpress', 'themify_upload_wordpress');
	
	///////////////////////////////////////////
	// Delete Image
	///////////////////////////////////////////
	function themify_delete_image(){
		if(file_exists("../".$_POST['file'])){
			unlink("../".$_POST['file']);
			echo "true";
		} else {
			echo "false";	
		}	
	}
	if($_GET['delete-image']){
		themify_delete_image();
	}
	add_action('wp_ajax_themify_delete_image', 'themify_delete_image');
	
	///////////////////////////////////////////
	// Version Updater
	///////////////////////////////////////////
	function themify_updater(){
		global $theme;
		if($_POST['type'] == 'theme'){
			$url = 'http://themify.me/files/'.strtolower($theme['Name']).'/'.strtolower($theme['Name']).'.zip';
			$dest = "../../";
		} else if($_POST['type'] == 'framework'){
			$url = 'http://themify.me/files/themify/themify.zip';
			$dest = "../";
		}
		if($_POST['login'] == "true"){
			if($_POST['username'] == "" || $_POST['password'] == ""){
				echo "false";
				return;
			} else {
				$ch = curl_init();
				curl_setopt($ch, CURLOPT_URL, 'http://themify.me/member/login.php');
				curl_setopt ($ch, CURLOPT_POST, 1);
				curl_setopt ($ch, CURLOPT_POSTFIELDS, 'amember_login='.$_POST['username'].'&amember_pass='.$_POST['password']);
				curl_setopt ($ch, CURLOPT_COOKIEJAR, 'cookie.txt');
				curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
				$store = curl_exec ($ch);
				curl_setopt($ch, CURLOPT_URL, $url);
				$content = curl_exec ($ch);
				curl_close ($ch);	
				unlink('cookie.txt');
				if(strpos($content, "301", 0) !== false || strpos($content, "302", 0) !== false){
					echo "false";	
					return;
				}
			}
		} else {
			if($fp=fopen($url, 'r')){
				$content = '';
				while ($line = fread($fp, 9999)) {
					$content .= $line;
				}
				fclose($fp);
			}
		}
		if(!is_dir(TEMPLATEPATH.'/temp')){		
			mkdir(TEMPLATEPATH.'/temp', 0777);
		}
		$newfile = TEMPLATEPATH.'/temp/temp.zip';
		if(!$fh=fopen($newfile, 'w')){
			echo "false";
			return;
		} else {
			fwrite($fh, $content);
			fclose($fh);			
			
			if(function_exists('themify_unzip')){
				themify_unzip('../temp/temp.zip', $dest);	
			} else {
				echo "false";
				return;
			}
			$handle = opendir("../temp/");
			while($file = readdir($handle)){
				if($file != "." && $file != ".."){
					unlink("../temp/".$file);
				}
			}
			rmdir("../temp/");
			echo "true";
			return;
		}
	}
	if($_GET['updater']){
		themify_updater();
	}
	add_action('wp_ajax_themify_updater', 'themify_updater');
	
?>