package_assets:         on          # (on, off, always)
embed_assets:           off          # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)
template_function:      _.template  # (defaults to the built-in micro-templating)
package_path:           packages    # (defaults to assets)
javascript_compressor:  yui         # (yui, closure)

javascripts:
  workspace:
    - public/javascripts/jquery-ui.min.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/jquery.condense.js
    - public/javascripts/facebox.js
    - public/javascripts/plugins.js
    # - public/javascripts/jquery.autocomplete.js
    - public/javascripts/jquery.indextank.ize.js
    - public/javascripts/querybuilder.js
    - public/javascripts/jquery.indextank.ajaxsearch.js
    # - public/javascripts/jquery.indextank.autocomplete.js
    - public/javascripts/jquery.indextank.renderer.js
    - public/javascripts/jquery.benvarim.search.autocomplete.js
    - public/javascripts/jquery.tmpl.min.js
    - public/javascripts/jquery.benvarim.facetsrenderer.js
    - public/javascripts/script.js



stylesheets:
  workspace:
    - public/stylesheets/style.css
    - public/stylesheets/jquery-ui-1.8.8.custom.css
    - public/stylesheets/facebox.css
    - public/stylesheets/buttons.css
    - public/stylesheets/grids.css
    - public/stylesheets/page.css
    - public/stylesheets/login-registration.css
